Document: sfuzz
Title: Debian sfuzz Manual
Author: <insert document author here>
Abstract: This manual describes what sfuzz is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sfuzz/sfuzz.sgml.gz

Format: postscript
Files: /usr/share/doc/sfuzz/sfuzz.ps.gz

Format: text
Files: /usr/share/doc/sfuzz/sfuzz.text.gz

Format: HTML
Index: /usr/share/doc/sfuzz/html/index.html
Files: /usr/share/doc/sfuzz/html/*.html
